---
- name: "number of ip in host"
  hosts: web
  ignore_unreachable: yes
  tasks:
    - name: "generating error"
      command: cat ~/project/.circleci/ansible/inventory.txt | wc -l
      register: command_result
      failed_when: >
        (command_result.stdout < 2) or 
        (command_result.stdout > 2)

- name: "configuration play."
  hosts: web
  ignore_unreachable: no
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for_connection: #https://docs.ansible.com/ansible/latest/collections/ansible/builtin/wait_for_connection_module.html
      # wait_for: timeout=600  https://docs.ansible.com/ansible/2.4/wait_for_module.html#:~:text=%20%20%20%20parameter%20%20%20,when%20look%20...%20%208%20more%20rows%20

    - name: "install python for Ansible."
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      changed_when: false

  # Get the environment variables from CircleCI and add to the EC2 instance
  environment:
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
    - TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
    - TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
    - TYPEORM_PORT: 5432
    - TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
    - TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
    - TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
    - TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
    - TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"

  roles:
    - configure-server
# Gather facts or a 'setup' task will connect to the managed host, run a script that collects a bunch of data, then it will populate the hostvars.

# If you don't gather facts, then those variables will never be collected and set. If you don't actually need the facts for your plays/tasks feel free to skip it. But many roles and plays you will use depend on knowing the OS/release/version and other things that are only detected when gathering facts.
